academy/urls.py
from django.urls import path
from academy import views

app_name = 'academy'
urlpatterns = [

    path('', views.AcademyClassView.as_view(), name='index'),

    path('introduce/', views.IntroduceView.as_view(), name='introduce'),

    path('mathClass/', views.MathClassView.as_view(), name='math'),

    path('introduce/brginner/', views.BeginnerView.as_view(), name='beginner'),

    path('introduce/middle/', views.MiddleView.as_view(), name='middle'),

    path('introduce/machineLearning/', views.MachineLearningView.as_view(),
         name='machineLearning'),

    path('introduce/computerVision/', views.ComputerVisionView.as_view(),
         name='computerVision'),

     path('introduce/nlp/', views.NlpView.as_view(), name='nlp'),
]

#  # Example: /academy/
#     path('', views.LevelLV.as_view(), name='index'),

#     # Example: /academy/level/, same as /academy/
#     path('level/', views.LevelLV.as_view(), name='level_list'),

#     # Example: /academy/level/99/
#     path('level/<int:pk>/', views.LevelDV.as_view(), name='level_detail'),

#     # Example: /academy/contents/99/
#     path('contents/<int:pk>/', views.ContentsDV.as_view(), name='contents_detail'),

arist/urls.py
from django.contrib import admin
from django.urls import path, include

from arist.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

import blog.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('business/', include('business.urls')),
    path('academy/', include('academy.urls')),
    path('lecture/', include('lecture.urls')),
    path('consulting/', include('consulting.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    # /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    # /blog/post/detail/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
]

academy/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Level(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('레벨에 대한 설명', max_length=100, blank=True)

    class Meta:
        ordering = ('-name',)

    def __str__(self):
        return self.name


class Contents(models.Model):
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.CharField(max_length=100, blank=True)
    place = models.CharField('PLACE', max_length=100)
    url = models.URLField('URL')
    start_dt = models.DateTimeField('Start Date')
    end_dt = models.DateTimeField('End Date')
    upload_dt = models.DateTimeField('Upload Date', auto_now_add=True)

    class Meta:
        ordering = ('-upload_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('academy:contents_detail', args=(self.id,))


class Images(models.Model):
    contents = models.ForeignKey(Contents, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to="academy/%Y/%m", blank=True, null=True)

    def __str__(self):
        return self.contents.title + " image"

academy/views.py
from django.views.generic import TemplateView, ListView, DetailView
from academy.models import Level, Contents

# Create your views here.


class LevelLV(ListView):
    model = Level


class ContentsDV(DetailView):
    model = Contents


class AcademyClassView(TemplateView):
    template_name = 'academy/academy_class.html'


class IntroduceView(TemplateView):
    template_name = 'academy/introduce.html'


class MathClassView(TemplateView):
    template_name = 'academy/math_class.html'


class BeginnerView(TemplateView):
    template_name = 'academy/introduce_beginner.html'


class MiddleView(TemplateView):
    template_name = 'academy/introduce_middle.html'


class MachineLearningView(TemplateView):
    template_name = 'academy/machineLearning.html'


class ComputerVisionView(TemplateView):
    template_name = 'academy/computerVision.html'

class NlpView(TemplateView):
    template_name = 'academy/nlp_class.html'

academy/templates/academy/academy_class.html
{% extends 'academy_base.html' %}

{% load static %}

{% block title %}수업소개 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }


    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .academy_title {
        color: white;
    }


    .academy_class_box {
        float: left;
        width: 50%;
    }

    .introduce_img {
        max-width: 50%;
        height: auto !important;
    }

    .introduce_img:hover {
        -ms-transform: scale(1.1);
        -webkit-transform: scale(1.1);
        transform: scale(1.1);
    }

    .introduce_title {
        font-size: 30pt;
    }
</style>
{% endblock %}

{% block content %}

<div id="carouselExampleControls" class="container carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="academy_class_box text-center">
                <span><strong class="introduce_title">인공지능</strong></span>
                <hr>
                <a href="{% url 'academy:introduce' %}">
                    <img class="introduce_img" src="{% static 'img/academy_class/AI_class.png' %}" alt="AI_class">
                </a>
            </div>
            <div class="academy_class_box text-center">
                <span><strong class="introduce_title">수학</strong></span>
                <hr>
                <a href="{% url 'academy:math' %}">
                    <img class="introduce_img" src="{% static 'img/academy_class/math_class.png' %}"
                        alt="beginner_class">
                </a>
            </div>
        </div>
    </div>

</div>
{% endblock %}

academy/templates/academy/computerVision.html
{% extends 'base.html' %}

{% load static %}

{% block title %}딥러닝 첫걸음 : Computer Vision - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }

    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .title {
        color: white;
    }

    img {
        width: 70%;
        height: 70%;
    }
</style>
{% endblock %}

{% block content %}
<div class="jumbotron text-center nav_img">
    <h2 class="title"><strong>딥러닝 첫걸음 : Computer Vision</strong></h2>
</div>


<div class="text-center">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision2.png' %}" alt="computer_vision2">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision3.PNG' %}" alt="computer_vision3">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision4.PNG' %}" alt="computer_vision4">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision5.PNG' %}" alt="computer_vision5">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision6.PNG' %}" alt="computer_vision6">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision7.PNG' %}" alt="computer_vision7">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision8.PNG' %}" alt="computer_vision8">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision9.PNG' %}" alt="computer_vision9">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision10.PNG' %}" alt="computer_vision10">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision11.PNG' %}" alt="computer_vision11">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision12.PNG' %}" alt="computer_vision12">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision13.PNG' %}" alt="computer_vision13">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision14.PNG' %}" alt="computer_vision14">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision15.PNG' %}" alt="computer_vision15">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision16.PNG' %}" alt="computer_vision16">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision17.PNG' %}" alt="computer_vision17">
    <img src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision18.PNG' %}" alt="computer_vision18">
</div>

{% endblock %}

academy/templates/academy/contents_detail.html
{% extends 'academy_base.html' %}

{% block title %}아카데미 상세 - ARIST{% endblock %}


{% block content %}


<div class="container">

    <h2 class="mt-5" style="margin-bottom: 50px;">{{ object.title }}</h2>
    <h4 style="margin-bottom: 30px;">{{ object.description }}</h3>
        <table style="margin-bottom: 50px;">
            <tr>
                <td>일자</td>
                <td>&nbsp;:&nbsp;</td>
                <td>{{ object.start_dt|date:"Y-m-d" }} ~ {{ object.end_dt|date:"Y-m-d" }}</td>
            </tr>
            <tr>
                <td>장소</td>
                <td>&nbsp;:&nbsp;</td>
                <td>{{ object.place }}</td>
            </tr>
            <tr>
                <td>수강신청</td>
                <td>&nbsp;:&nbsp;</td>
                <td><a href="{{ object.url }}">수강신청 바로가기</a></td>
            </tr>
        </table>

        {% for image in contents.images_set.all %}
        <div class="text-center">
            <img style="width: 60%; height: 60%;" src="{{ image.image.url }}">
        </div>
        {% endfor %}

</div>
{% endblock %}

academy/templates/academy/introduce.html
{% extends 'academy_base.html' %}

{% load static %}

{% block title %}수업소개 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }


    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .academy_title {
        color: white;
    }

    .introduce_box {
        float: left;
        width: 50%;
    }

    .introduce_img {
        max-width: 90%;
        height: auto !important;
    }

    .introduce_img:hover {
        -ms-transform: scale(1.1);
        -webkit-transform: scale(1.1);
        transform: scale(1.1);
    }

    .introduce_background {
        width: 550px;
        height: 366px;
        background-color: white;
    }

    .introduce_title {
        font-size: 13pt;
    }
</style>
{% endblock %}

{% block content %}

<div id="carouselExampleControls" class="container carousel slide" data-ride="carousel">

    <div class="text-center">
        <span><strong style="font-size: 20pt;">딥러닝 교육과정</strong></span>
    </div>

    <br>
    <br>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">딥러닝 첫걸음 : </strong>NLP</span>
                <hr>
                <a href="{% url 'academy:nlp' %}">
                    <img class="introduce_img" src="{% static 'img/deepLearning_class_img/NLP_class/NLP_thumbnail.png' %}"
                        alt="NLP_class">
                </a>
            </div>
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">딥러닝 첫걸음 : </strong>Computer Vision</span>
                <hr>
                <a href="{% url 'academy:computerVision' %}">
                    <img class="introduce_img" src="{% static 'img/deepLearning_class_img/computer_vision/computer_vision1.png' %}"
                        alt="computerVision_class">
                </a>
            </div>
        </div>

        <div class="carousel-item">
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">딥러닝 첫걸음</strong>(입문반)</span>
                <hr>
                <a href="{% url 'academy:beginner' %}">
                    <img class="introduce_img" src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner1.png' %}"
                        alt="beginner_class">
                </a>
            </div>
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">딥러닝 따라잡기</strong>(중급반)</span>
                <hr>
                <a href="{% url 'academy:middle' %}">
                    <img class="introduce_img" src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle1.png' %}"
                        alt="middle_class">
                </a>
            </div>
        </div>

        <!-- 페이지 샘플 -->
        <!-- <div class="carousel-item">
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">&nbsp;</strong></span>
                <hr>
                <p class="introduce_img"></p>
            </div>
            <div class="introduce_box text-center">
                <span><strong class="introduce_title">&nbsp;</strong></span>
                <hr>
                <p class="introduce_img"></p>
            </div>
        </div> -->

        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

    </div>

</div>

<hr>


<div class="container" style="margin-top: 50px;">

    <div class="text-center">
        <span><strong style="font-size: 20pt;">머신러닝 교육과정</strong></span>
    </div>

    <br>
    <br>

    <div class="introduce_box text-center">
        <span><strong class="introduce_title">머신러닝 첫걸음</strong>(입문반)</span>
        <hr>
        <a href="{% url 'academy:machineLearning' %}">
            <img class="introduce_img" src="{% static 'img/machineLearning_class_img/machineLearning.png' %}"
                alt="machineLearning_class">
        </a>
    </div>
    <div class="text-center">
        <span><strong class="introduce_title">&nbsp;</strong></span>
        <hr>
        <p class="introduce_background"></p>
    </div>

</div>
{% endblock %}

academy/templates/academy/introduce_beginner.html
{% extends 'base.html' %}

{% load static %}

{% block title %}딥러닝 첫걸음 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }

    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .title {
        color: white;
    }

    img {
        width: 70%;
        height: 70%;
    }
</style>
{% endblock %}

{% block content %}
<div class="jumbotron text-center nav_img">
    <h2 class="title"><strong>딥러닝 첫걸음</strong></h2>
</div>


<div class="text-center">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner2.JPG' %}" alt="introduce_beginner2">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner3.JPG' %}" alt="introduce_beginner3">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner4.JPG' %}" alt="introduce_beginner4">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner5.JPG' %}" alt="introduce_beginner5">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner6.JPG' %}" alt="introduce_beginner6">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner7.JPG' %}" alt="introduce_beginner7">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner8.JPG' %}" alt="introduce_beginner8">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner9.JPG' %}" alt="introduce_beginner9">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner10.JPG' %}" alt="introduce_beginner10">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner11.JPG' %}" alt="introduce_beginner11">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner12.JPG' %}" alt="introduce_beginner12">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner13.JPG' %}" alt="introduce_beginner13">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner14.JPG' %}" alt="introduce_beginner14">
    <img src="{% static 'img/deepLearning_class_img/introduce_beginner/introduce_beginner15.JPG' %}" alt="introduce_beginner15">
</div>

{% endblock %}

academy/templates/academy/introduce_middle.html
{% extends 'base.html' %}

{% load static %}

{% block title %}딥러닝 따라잡기 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }

    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .title {
        color: white;
    }

    img {
        width: 70%;
        height: 70%;
    }
</style>
{% endblock %}

{% block content %}
<div class="jumbotron text-center nav_img">
    <h2 class="title"><strong>딥러닝 따라잡기</strong></h2>
</div>


<div class="text-center">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle2.JPG' %}" alt="introduce_middle2">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle3.JPG' %}" alt="introduce_middle3">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle4.JPG' %}" alt="introduce_middle4">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle5.JPG' %}" alt="introduce_middle5">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle6.JPG' %}" alt="introduce_middle6">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle7.JPG' %}" alt="introduce_middle7">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle8.JPG' %}" alt="introduce_middle8">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle9.JPG' %}" alt="introduce_middle9">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle10.JPG' %}" alt="introduce_middle10">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle11.JPG' %}" alt="introduce_middle11">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle12.JPG' %}" alt="introduce_middle12">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle13.JPG' %}" alt="introduce_middle13">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle14.JPG' %}" alt="introduce_middle14">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle15.JPG' %}" alt="introduce_middle15">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle16.JPG' %}" alt="introduce_middle16">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle17.JPG' %}" alt="introduce_middle17">
    <img src="{% static 'img/deepLearning_class_img/introduce_middle/introduce_middle18.JPG' %}" alt="introduce_middle18">
</div>

{% endblock %}

academy/templates/academy/level_list.html
{% extends 'academy_base.html' %}

{% block title %}아카데미 - ARIST{% endblock %}

{% block content %}



<div class="container">

    {% for item in object_list %}
    <div class="mt-5">
        <span class="h2">{{ item.name }}</span>&emsp;
        <span class="font-italic h5">{{ item.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">
    <div class="row">
        {% for contents in item.contents_set.all|slice:":4" %}
        <div class="ml-5">
            <div class="thumbnail">
                <a href="{{ contents.get_absolute_url }}">
                    {% for image in contents.images_set.all|slice:":1" %}
                    <img src="{{ image.image.url }}" style="width: 230px; height: 300px;">
                    {% endfor %}
                </a>
            </div>
            <table>
                <tr>
                    <td class="font-italic">수업</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td class="font-italic">{{ contents.title }}
                    </td>
                </tr>
                <tr>
                    <td class="font-italic">수업기간</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td class="font-italic">{{ contents.start_dt|date:"Y-m-d" }} ~ {{ contents.end_dt|date:"Y-m-d" }}
                    </td>
                </tr>
                <tr>
                    <td class="font-italic">수업시간</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td class="font-italic">{{ contents.start_dt|time }} ~ {{ contents.end_dt|time }}
                    </td>
                </tr>
            </table>
        </div>
        {% endfor %}
    </div>

    {% endfor %}

</div>
{% endblock %}

academy/templates/academy/machineLearning.html
{% extends 'base.html' %}

{% load static %}

{% block title %}머신러닝 첫걸음 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }

    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .title {
        color: white;
    }

    img {
        width: 70%;
        height: 70%;
    }
</style>
{% endblock %}

{% block content %}
<div class="jumbotron text-center nav_img">
    <h2 class="title"><strong>머신러닝 첫걸음</strong></h2>
</div>


<div class="text-center">
    <img src="{% static 'img/machineLearning_class_img/machineLearning_calss.png' %}" alt="machineLearning_calss">
    <img src="{% static 'img/machineLearning_class_img/machineLearning1.PNG' %}" alt="machineLearning1">
    <img src="{% static 'img/machineLearning_class_img/machineLearning2.PNG' %}" alt="machineLearning2">
    <img src="{% static 'img/machineLearning_class_img/machineLearning3.PNG' %}" alt="machineLearning3">
    <img src="{% static 'img/machineLearning_class_img/machineLearning4.PNG' %}" alt="machineLearning4">
    <img src="{% static 'img/machineLearning_class_img/machineLearning5.PNG' %}" alt="machineLearning5">
    <img src="{% static 'img/machineLearning_class_img/machineLearning6.PNG' %}" alt="machineLearning6">
    <img src="{% static 'img/machineLearning_class_img/machineLearning7.PNG' %}" alt="machineLearning7">
    <img src="{% static 'img/machineLearning_class_img/machineLearning8.PNG' %}" alt="machineLearning8">
    <img src="{% static 'img/machineLearning_class_img/machineLearning9.PNG' %}" alt="machineLearning9">
    <img src="{% static 'img/machineLearning_class_img/machineLearning10.PNG' %}" alt="machineLearning10">
    <img src="{% static 'img/machineLearning_class_img/machineLearning11.PNG' %}" alt="machineLearning11">
    <img src="{% static 'img/machineLearning_class_img/machineLearning12.PNG' %}" alt="machineLearning12">
    <img src="{% static 'img/machineLearning_class_img/machineLearning13.PNG' %}" alt="machineLearning13">
    <img src="{% static 'img/machineLearning_class_img/machineLearning14.PNG' %}" alt="machineLearning14">
</div>

{% endblock %}

academy/templates/academy/math_class.html
{% extends 'academy_base.html' %}

{% load static %}

{% block title %}수업소개 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }


    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .academy_title {
        color: white;
    }

    .introduce_img {
        max-width: 100%;
        height: auto !important;
    }

    .mathBook {
        max-width: 80%;
        height: auto !important;
    }

    .introduce_title {
        font-size: 20pt;
    }
</style>
{% endblock %}

{% block content %}

<div id="carouselExampleControls" class="container carousel slide" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <div class="academy_class_box text-center">
                <img class="introduce_img" src="{% static 'img/academy_class/math_introduce.png' %}"
                    alt="math_introduce">
            </div>
        </div>
    </div>

</div>

<div class="container" style="margin-top: 50px;">

    <div class="text-center">
        <span><strong style="font-size: 20pt;">수학 교육과정</strong></span>
    </div>

    <br>
    <br>

    <table>
        <tr class="introduce_box text-center">
            <td><span class="introduce_title">미적분학</span></td>
            <td><span class="introduce_title">선형대수</strong></span></td>
            <td><span class="introduce_title">해석학</strong></span></td>
        </tr>
        <tr class="introduce_box text-center">
            <td><img class="mathBook" src="{% static 'img/academy_class/book1.png' %}" alt="machineLearning_class"></td>
            <td><img class="mathBook" src="{% static 'img/academy_class/book2.png' %}" alt="machineLearning_class"></td>
            <td><img class="mathBook" src="{% static 'img/academy_class/book3.png' %}" alt="machineLearning_class"></td>
        </tr>
    </table>
    <div class="introduce_box text-center">


    </div>

</div>
{% endblock %}

academy/templates/academy/nlp_class.html
{% extends 'base.html' %}

{% load static %}

{% block title %}딥러닝 첫걸음 - ARIST{% endblock %}

{% block extra-style %}
<style>
    body {
        overflow-x: hidden;
        overflow-y: auto;
    }

    .nav_img {
        background-image: url("{% static 'img/academy1.jpg' %}");
        background-size: cover;
    }

    .title {
        color: white;
    }

    img {
        width: 70%;
        height: 70%;
    }
</style>
{% endblock %}

{% block content %}
<div class="jumbotron text-center nav_img">
    <h2 class="title"><strong>딥러닝 첫걸음</strong></h2>
</div>


<div class="text-center">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class.png' %}" alt="NLP_class">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class1.PNG' %}" alt="NLP_class1">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class2.PNG' %}" alt="NLP_class2">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class3.PNG' %}" alt="NLP_class3">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class4.PNG' %}" alt="NLP_class4">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class5.PNG' %}" alt="NLP_class5">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class6.PNG' %}" alt="NLP_class6">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class7.PNG' %}" alt="NLP_class7">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class8.PNG' %}" alt="NLP_class8">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class9.PNG' %}" alt="NLP_class9">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class10.PNG' %}" alt="NLP_class10">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class11.PNG' %}" alt="NLP_class11">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class12.PNG' %}" alt="NLP_class12">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class13.PNG' %}" alt="NLP_class13">
    <img src="{% static 'img/deepLearning_class_img/NLP_class/NLP_class14.PNG' %}" alt="NLP_class14">
</div>

{% endblock %}