academy/urls.py
from django.urls import path
from academy import views

app_name = 'academy'
urlpatterns = [

    path('', views.AcademyClassView.as_view(), name='index'),

    path('introduce/', views.IntroduceView.as_view(), name='introduce'),

    path('mathClass/', views.MathClassView.as_view(), name='math'),

    path('introduce/brginner/', views.BeginnerView.as_view(), name='beginner'),

    path('introduce/middle/', views.MiddleView.as_view(), name='middle'),

    path('introduce/machineLearning/', views.MachineLearningView.as_view(),
         name='machineLearning'),

    path('introduce/computerVision/', views.ComputerVisionView.as_view(),
         name='computerVision'),

     path('introduce/nlp/', views.NlpView.as_view(), name='nlp'),
]

#  # Example: /academy/
#     path('', views.LevelLV.as_view(), name='index'),

#     # Example: /academy/level/, same as /academy/
#     path('level/', views.LevelLV.as_view(), name='level_list'),

#     # Example: /academy/level/99/
#     path('level/<int:pk>/', views.LevelDV.as_view(), name='level_detail'),

#     # Example: /academy/contents/99/
#     path('contents/<int:pk>/', views.ContentsDV.as_view(), name='contents_detail'),

arist/urls.py
from django.contrib import admin
from django.urls import path, include

from arist.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

import blog.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('business/', include('business.urls')),
    path('academy/', include('academy.urls')),
    path('lecture/', include('lecture.urls')),
    path('consulting/', include('consulting.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),
    # /blog/post/
    path('post/', views.PostLV.as_view(), name='post_list'),
    # /blog/post/detail/
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
]

business/urls.py
from django.urls import path
from business import views

app_name = 'business'
urlpatterns = [
    # Example: /business/
    path('', views.BusinessView.as_view(), name='index'),
]

consulting/urls.py
from django.urls import path
from consulting import views

app_name = 'consulting'
urlpatterns = [
    path('', views.AiConsultingView.as_view(), name='index'),
]

lecture/urls.py
from django.urls import path
from lecture import views

app_name = 'lecture'
urlpatterns = [
    # Example: /lecture/
    path('', views.LectureView.as_view(), name='index'),
]

templates/academy_base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}ARIST{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra-style %}{% endblock %}
</head>

<body>

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <a class="arist_logo_box" href="{% url 'home' %}">
            <img class="arist_logo" src="{% static 'img/ARIST_logo.png' %}" alt="arist_logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'business:index' %}">Business</a>
                </li>
                <li class="nav-item dropdown mx-1 btn">
                    <a class="nav-link dropdown-toggle" href="{% url 'academy:index' %}" id="navbarDropdown"
                        role="button" aria-haspopup="true" aria-expanded="false">
                        Academy
                    </a>
                    <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'academy:introduce' %}">인공지능</a>
                        <a class="dropdown-item" href="{% url 'academy:math' %}">수학</a>
                    </div>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'consulting:index' %}">AI컨설팅</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'lecture:index' %}">기업체출강</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="jumbotron text-center nav_img">
        <h2 class="academy_title"><strong>Academy</strong></h2>
    </div>

    {% block content %}{% endblock %}

    {% block footer %}
    <footer style="margin-top: 50px; color: darkgray;">
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg bt">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'home' %}">ARIST</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black"
                        href="{% url 'business:index' %}">Business</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black"
                        href="{% url 'academy:index' %}">Academy</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'consulting:index' %}">AI컨설팅</a>
                </li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'lecture:index' %}">기업체출강</a>
                </li>
            </ul>
        </nav>

        <nav class="navbar navbar-dark bg-dark navbar-expand-lg bt">
            <ul class="nav flex-column" style="font-size: 11px;">
                <li>주소 : 대전광역시 서구 월평북로 85, 401호</li>
                <li>전화번호 : 042-721-1023</li>
                <li>팩스번호 : 042-471-8903</li>
                <li>이메일 : contact@arist.io</li>
            </ul>
        </nav>
    </footer>
    {% endblock %}



    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155052021-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-155052021-1');
    </script>

    {% block extra-script %}{% endblock %}
</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}ARIST{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra-style %}{% endblock %}
</head>

<body>

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <a class="arist_logo_box" href="{% url 'home' %}">
            <img class="arist_logo" src="{% static 'img/ARIST_logo.png' %}" alt="arist_logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'business:index' %}">Business</a>
                </li>
                <li class="nav-item dropdown mx-1 btn text-center">
                    <a class="nav-link dropdown-toggle" href="{% url 'academy:index' %}" id="navbarDropdown"
                        role="button" aria-haspopup="true" aria-expanded="false">
                        Academy
                    </a>
                    <div class="dropdown-menu text-center" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'academy:introduce' %}">인공지능</a>
                        <a class="dropdown-item" href="{% url 'academy:math' %}">수학</a>
                    </div>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'consulting:index' %}">AI컨설팅</a>
                </li>
                <li class="nav-item mx-1 btn">
                    <a class="nav-link" href="{% url 'lecture:index' %}">기업체출강</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content %}{% endblock %}

    {% block footer %}
    <footer style="margin-top: 50px; color: darkgray;">
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg bt">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'home' %}">ARIST</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black"
                        href="{% url 'business:index' %}">Business</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black"
                        href="{% url 'academy:index' %}">Academy</a></li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'consulting:index' %}">AI컨설팅</a>
                </li>
                <li class="nav-item mx-1 btn"><a class="nav-link text-black" href="{% url 'lecture:index' %}">기업체출강</a>
                </li>
            </ul>
        </nav>

        <nav class="navbar navbar-dark bg-dark navbar-expand-lg bt">
            <ul class="nav flex-column" style="font-size: 11px;">
                <li>주소 : 대전광역시 서구 월평북로 85, 401호</li>
                <li>전화번호 : 042-721-1023</li>
                <li>팩스번호 : 042-471-8903</li>
                <li>이메일 : contact@arist.io</li>
            </ul>
        </nav>
    </footer>
    {% endblock %}




    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}"></script>
    <!-- <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script> -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-155052021-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-155052021-1');
    </script>


    {% block extra-script %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}ARIST{% endblock %}

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/main_img1.jpg' %}" class="d-block w-100" alt="main_image">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/main_img2.jpg' %}" class="d-block w-100" alt="main_image">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="jumbotron vision_box">
    <div class="text-center arist_vision">
        <span>비전</span>
        <p>소통과 화합으로 새로운 가치 창조</p>
    </div>

    <div class="row">
        <div class="col-sm-4 text-center">
            <h4><strong></strong></h4>
            <img class="vision_icon" src="{% static 'img/study.png' %}" alt="Realization of value">
            <p>자기 개발을 통한 인간 가치의 실현</p>
        </div>
        <div class="col-sm-4 text-center">
            <h4><strong></strong></h4>
            <img class="vision_icon" src="{% static 'img/classroom.png' %}" alt="Talent Education">
            <p>사회에 기여할 수 있는 인재 교육</p>
        </div>
        <div class="col-sm-4 text-center">
            <h4><strong></strong></h4>
            <img class="vision_icon" src="{% static 'img/develop.png' %}" alt="Technology development">
            <p>더불어 잘 사는 세상을 위한 기술 개발</p>
        </div>
    </div>
</div>

<div class="academy_box text-center row">
    
    <div class="academy_box_img_out col-sm-6">
        <a href="{% url 'academy:index' %}">
            <div class="text-center academy_box_img_in">
                <img src="/static/img/academy2.jpg" alt="academy" style="margin: auto;">
                <!-- onmouseover="this.src='/static/img/question.png'" onmouseout="this.src='/static/img/academy2.jpg'" -->
            </div>
        </a>
    </div>

    <div class="academy_box_contents col-sm-6">
        <div class="text-center academy_box_contents_in">
            <p><span style="font-size: 3rem;"><strong>Academy</strong></span></p>
            <p>인공지능 인력의 저변확대를 위한 교육 시스템</p>
            <p>누구나 쉽게 배울 수 있는 실습 위주의 교육</p>
            <p>원리 이해를 통한 인재의 고급화</p>
        </div>
    </div>

</div>

<div class="question_box">
    <div class="text-center">
        <img class="question_img" src="{% static 'img/question.jpg' %}" alt="question">
    </div>
</div>

{% endblock %}